# Generated by Django 5.2 on 2025-04-06 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('main_image', models.ImageField(upload_to='events/images/')),
                ('event_story', models.TextField(help_text='Enter in markdown format')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('location_name', models.CharField(max_length=200)),
                ('location_desc', models.TextField(help_text='Enter in markdown format')),
                ('location_lat', models.FloatField(blank=True, null=True)),
                ('location_lon', models.FloatField(blank=True, null=True)),
                ('public_transport_desc', models.TextField(blank=True, help_text='Enter in markdown format')),
                ('fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fee_desc', models.TextField(blank=True, help_text='Enter in markdown format')),
                ('house_desc', models.TextField(blank=True, help_text='Enter in markdown format')),
                ('registration_form', models.URLField(blank=True)),
                ('activity_ideas', models.TextField(blank=True, help_text='Enter in markdown format')),
                ('organizers', models.TextField(blank=True, help_text='Enter in markdown format')),
            ],
        ),
        migrations.CreateModel(
            name='EventProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day_activity', models.TextField(blank=True, help_text='Enter in markdown format')),
                ('evening_activity', models.TextField(blank=True, help_text='Enter in markdown format')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_days', to='web.event')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='events/images/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='web.event')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GeneralEventInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_description', models.TextField(blank=True, help_text='Enter in markdown format')),
                ('food_description', models.TextField(blank=True, help_text='Enter in markdown format')),
                ('registration_description', models.TextField(blank=True, help_text='Enter in markdown format')),
            ],
            options={
                'verbose_name': 'General Event Information',
                'verbose_name_plural': 'General Event Information',
            },
        ),
        migrations.DeleteModel(
            name='TodoItem',
        ),
    ]
