# Generated by Django 5.2 on 2025-04-09 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
