# Generated by Django 5.2 on 2025-04-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_event_end_date_alter_event_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='public_transport_desc',
            new_name='how_to_get_there',
        ),
        migrations.AddField(
            model_name='event',
            name='couchsurfing_link',
            field=models.URLField(blank=True, help_text='Link to couchsurfing event'),
        ),
        migrations.AddField(
            model_name='event',
            name='googlemaps_embed',
            field=models.TextField(blank=True, help_text='Google Maps embed code'),
        ),
        migrations.AddField(
            model_name='event',
            name='town',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
