# Generated by Django 5.2 on 2025-04-10 14:48

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_event_max_participants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='what_to_bring',
            field=models.TextField(blank=True, help_text='Enter in markdown format'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='address',
            field=models.TextField(blank=True, help_text="Your address. This is not mandatory, but it helps us to know where you're from.", max_length=200),
        ),
        migrations.AlterField(
            model_name='registration',
            name='country',
            field=django_countries.fields.CountryField(help_text='What country do you identify with? Not related to your current address, we will just show this as a flag next to your name in the registrations.', max_length=2),
        ),
        migrations.AlterField(
            model_name='registration',
            name='potluck',
            field=models.TextField(help_text='What do you plan to bring for the Potluck aka. International Dinner? Check the event program for more info.', max_length=200),
        ),
    ]
