# Generated by Django 5.2 on 2025-04-07 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_rename_public_transport_desc_event_how_to_get_there_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='location_name',
            new_name='house_name',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='town',
            new_name='town_name',
        ),
    ]
