# Generated by Django 5.2 on 2025-04-07 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_rename_location_name_event_house_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_story',
            field=models.TextField(blank=True, help_text='Enter in markdown format'),
        ),
        migrations.AlterField(
            model_name='event',
            name='town_name',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='AccommodationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='events/accommodations/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodation_images', to='web.event')),
            ],
            options={
                'verbose_name': 'Accommodation Image',
                'verbose_name_plural': 'Accommodation Images',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SurroundingsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='events/surroundings/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surroundings_images', to='web.event')),
            ],
            options={
                'verbose_name': 'Surroundings Image',
                'verbose_name_plural': 'Surroundings Images',
                'ordering': ['order'],
            },
        ),
    ]
