# Generated by Django 5.2 on 2025-04-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_event_event_story_alter_event_town_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_state',
            field=models.CharField(blank=True, help_text='State of the registration form', max_length=200),
        ),
    ]
