# Generated by Django 5.2 on 2025-04-09 11:35

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_event_registration_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='registration_form',
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_state',
            field=models.CharField(choices=[('soon', 'Registrations opening soon'), ('open', 'Registrations are open'), ('closed', 'Registrations closed')], default='soon', help_text='Current state of event registration', max_length=30),
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(max_length=200)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('phone', models.CharField(max_length=20)),
                ('special_diets', models.TextField(blank=True, help_text='Dietary restrictions or allergies we should know about', max_length=200)),
                ('checkbox1', models.BooleanField(default=False, help_text='I have read the entire event description and I agree to the format')),
                ('checkbox2', models.BooleanField(default=False, help_text='I am ready to help out with cooking, keeping the house clean, and other tasks')),
                ('checkbox3', models.BooleanField(default=False, help_text='I agree to be respectful and inclusive to all other participants')),
                ('checkbox4', models.BooleanField(default=False, help_text="I notice that some pictures of the event might be published on this website after the event and I will talk to the organizers if I don't agree")),
                ('potluck', models.TextField(help_text='What do you plan to bring for the Potluck / International Dinner?', max_length=200)),
                ('activity_idea', models.TextField(blank=True, help_text='Do you have an activity idea that you would like to suggest for other participants that we should keep some time in the program for?', max_length=200)),
                ('other_comments', models.TextField(blank=True, help_text='Any other comments or questions?', max_length=500)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=100)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='web.event')),
            ],
        ),
    ]
