# Generated by Django 5.2 on 2025-04-09 12:41

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_remove_event_registration_form_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Internal notes about this coupon')),
                ('discount_amount', models.DecimalField(decimal_places=2, help_text='Amount to discount in CHF', max_digits=10)),
                ('expiry_date', models.DateField(help_text='Coupon expires at the end of this day')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='registration',
            name='bring_a_friend',
            field=models.BooleanField(default=False, help_text='If you want to sign up together with a friend. It is recommended however that your friend fills the registration for themselves as well to get all relevant information.'),
        ),
        migrations.AddField(
            model_name='registration',
            name='checkbox5',
            field=models.BooleanField(default=False, help_text='I have understood that I have to forward all relevant information to the friend I signed up together with me'),
        ),
        migrations.AddField(
            model_name='registration',
            name='coupon_code',
            field=models.CharField(blank=True, help_text='Enter a discount code if you have one', max_length=50),
        ),
        migrations.AddField(
            model_name='registration',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='friend_name',
            field=models.CharField(blank=True, help_text="Name of your friend if you're bringing someone", max_length=200),
        ),
        migrations.AddField(
            model_name='registration',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.EmailField(help_text='I will send you event related information to your email, make sure it works', max_length=254),
        ),
        migrations.AlterField(
            model_name='registration',
            name='first_name',
            field=models.CharField(help_text='This will be public to other participants', max_length=200),
        ),
        migrations.AlterField(
            model_name='registration',
            name='last_name',
            field=models.CharField(help_text="This won't be shared on the website", max_length=200),
        ),
        migrations.AlterField(
            model_name='registration',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='I might use this to call you for any question or organisational things. There will be a Signal group for the event for which you can sign up if you want, you will receive the link as an email.', max_length=128, region='CH'),
        ),
        migrations.AddField(
            model_name='registration',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='web.coupon'),
        ),
    ]
