# Generated by Django 5.2 on 2025-04-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_coupon_registration_bring_a_friend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sender_list_id',
            field=models.CharField(blank=True, help_text='Sender.net list ID specific to this event', max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='checkbox1',
            field=models.BooleanField(default=False, verbose_name='I have read the entire event description and I agree to the format'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='checkbox2',
            field=models.BooleanField(default=False, verbose_name='I am ready to help out with cooking, keeping the house clean, and other tasks'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='checkbox3',
            field=models.BooleanField(default=False, verbose_name='I agree to be respectful and inclusive to all other participants'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='checkbox4',
            field=models.BooleanField(default=False, verbose_name="I notice that some pictures of the event might be published on this website after the event and I will talk to the organizers if I don't agree"),
        ),
        migrations.AlterField(
            model_name='registration',
            name='checkbox5',
            field=models.BooleanField(default=False, verbose_name='I have understood that I have to forward all relevant information to the friend I signed up together with me'),
        ),
    ]
